#! /bin/sh

$XDG_CONFIG_HOME/polybar/launch.sh &
sxhkd &

bspc monitor -d I II III IV V VI VII VII IX X
#bspc monitor eDP1 I III V VII IX
#bspc monitor DP1 II IV VI VIII X

#bspc desktop -f 1

bspc config border_width         2
bspc config window_gap           0
bspc config top_padding          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled
