#!/bin/sh

res=""
total_bat=0

for bat in /sys/class/power_supply/BAT?
do
	if [ "$(cat $bat/status)" == "Charging" ];
	then
		res="⚡"

	else
		total_bat=$(echo $total_bat + $(cat $bat/capacity) | bc)
	fi;
done

if [ -z "$res" ] && [ "$total_bat" -lt 15 ];
then
	res="⚠"
fi;


echo "$res"
