#!/bin/sh


primary=$(xrandr | grep primary | cut -d' ' -f1)

secondary=$(xrandr | grep -v primary | grep ' connected' | head -n 1 | cut -d' ' -f1)

if [ -z "$secondary" ]
then
	echo "No secondary monitor connected."
else
	secondary_connected=$(xrandr | grep $secondary | grep mm)

	if [ -z "$secondary_connected" ]
	then
		xrandr --output $secondary --auto --right-of $primary
	else
		xrandr --output $secondary --off
	fi
fi
