#!/bin/sh
# /usr/local/bin

file=$(find ~/.config/help -type f | sed 's/.*\/help\///' | dmenu -fn "Source Code Pro:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#16A085" -sf "#eeeeee")

[ -n "$file" ] && cat ~/.config/help/"$file" | dmenu -fn "Source Code Pro:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#16A085" -sf "#eeeeee" -l 20
