#!/bin/sh
# /usr/local/bin
wq
res=$(echo -e "lock\nexit\nreboot\nshutdown\nsuspend" | dmenu)

case "$res" in
	lock)			lock ;;
	exit)			bspc quit ;;
	reboot)		reboot ;;
	shutdown)	shutdown now ;;
	suspend)	mysuspend ;;
esac
