#!/bin/sh
# /usr/local/bin

res=$(echo -e "lock\nexit\npoweroff" | dmenu -fn "Source Code Pro:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#16A085" -sf "#eeeeee")

if [ -n "$res" ]
then
	if [ "lock" == "$res" ]
	then
		mandellock
	else
		if [ "exit" == "$res" ]
		then
			bspc quit
		else
			if [ "poweroff" == "$res" ]
			then
				poweroff
			fi
		fi
	fi
fi
