#!/bin/sh

# Credit to luke smith: https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/statusbar/nettraf

# Measure bandwidth used from last run

# /sys/class/net/w*/statistics/rx_bytes
#		total received bytes
# /sys/class/net/w*/statistics/tx_bytes
#		total transferred bytes

update() {
	sum=0
	for arg; do
		read -r i < "$arg"
		sum=$(( sum + i ))
	done
	cache=${XDG_CACHE_HOME:-$HOME/.cache}/${1##*/}
	[ -f "$cache" ] && read -r old < "$cache" || old=0
	printf %d\\n "$sum" > "$cache"
	printf %d\\n $(( (sum - old) / 1024 ))
}

rx=$(update /sys/class/net/[ew]*/statistics/rx_bytes)
tx=$(update /sys/class/net/[ew]*/statistics/rx_bytes)

printf "↓%dKiB ↑%dKiB\\n" "$rx" "$tx"
