#!/bin/sh

#ping -q -c 1 1.1.1.1 >/dev/null &&
#curl -s "wttr.in/?m" > "$HOME/.local/share/weatherreport" &&
#notify-send "Weather" "Fetched new weather forecast." &&

# WEATHER
[ "$(stat -c %y "$HOME/.local/share/weatherreport" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] &&
sed '16q;d' "$HOME/.local/share/weatherreport" | grep -wo "[0-9]*%" | sort -n | sed -e '$!d' | sed -e "s/^/🌢 /g" | tr -d '\n' &&
sed '13q;d' "$HOME/.local/share/weatherreport" | grep -o "m\\(-\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print " ❄",$1 "°","🌣",$2 "°"}' &&
echo "$delim"


