#! /bin/sh

$XDG_CONFIG_HOME/polybar/launch.sh &
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# bspc desktop -f 1


bspc config border_width         1
bspc config window_gap           0
bspc config top_padding          0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

bspc config normal_border_color "#222"
bspc config active_border_color "#85146e"
bspc config focused_border_color "#85146e"
bspc config presel_feedback_color	"#85146e"

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled
bspc rule -a zoom state=tiled
