#! /bin/sh

$XDG_CONFIG_HOME/polybar/launch.sh &
sxhkd &

primary_monitor=$(xrandr | grep primary | cut -d' ' -f1)
secondary_monitor=$(xrandr | grep -v primary | grep ' connected' | head -n 1 | cut -d' ' -f1)

if [ ! -z "$secondary_monitor" ]
then
	bspc monitor $primary_monitor -d 1 2 3 4 5 6
	bspc monitor $secondary_monitor -d 7 8 9 0
else
	bspc monitor $primary_monitor -d 1 2 3 4 5 6 7 8 9 0
fi

bspc desktop -f 1


bspc config border_width         1
bspc config window_gap           0
bspc config top_padding          20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

bspc config normal_border_color "#222"
bspc config active_border_color "#85146e"
bspc config focused_border_color "#85146e"
bspc config presel_feedback_color	"#85146e"

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled
bspc rule -a zoom state=tiled
